### ISSUE TITLE
Closed source licensing?

### ISSUE THREAD

**Issue by Toddler-Boy** [daglem/reSID#1]
Would it be possible to license reSID for a closed-source project in exchange for a license fee?

Any potential changes would be open-sourced in a cloned GitHub repository, of course.

**Comment by daglem** [comment]
Thank you for asking.

I don't think commercial licensing of reSID will be worth my while, and so I have decided to keep it open source only.

**Comment by Toddler-Boy** [comment]
Is there another way to get in touch to discuss possible licensing fees or even royalties in private?

**Comment by daglem** [comment]
There is a contact email address at the top of all source files. However as I said, I am keeping the project open source only.

**Comment by Toddler-Boy** [comment]
I'm not suggesting taking it closed source. Just that we are allowed to use it in a close-sourced project as well.

**Comment by daglem** [comment]
I understood you perfectly. Making the project closed source will never be an option. However as I said, I really don't think commercial (dual) licensing will be worth my while, and so I have decided to keep the project open source *only*.
